on: [push, pull_request]

name: CI

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - uses: joschi/setup-jdk@v2
        with:
          java-version: '8'

      - run: "wget -O gson.jar https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.2/gson-2.8.2.jar"
        working-directory: src/

      - name: Compile
        run: javac -cp "." $(find . -name "*.java")
        shell: bash
        working-directory: src/